version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  myapp:
    build: .
    restart: "no"
    depends_on:
      - database
    ports:
      - 8080:8080