version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  myapp:
    build: .
    restart: "no"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080