name: CI Tests for database

on:
  push:
    branches: [ "review_branch" ]
  pull_request:
    branches: [ "review_branch" ]

jobs:

  TestForDatabase:
    name: Test for database
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: test-database
      run: go test -coverprofile=coverage.out -v ./data-base

  TestAndLint:
    name: Tests and Linters
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Linters
        run: |
          curl -sSfl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

          golangci-lint run --config=golangci-lint.yml

      - name: test-transformer
        run: go test -coverprofile=coverage.out -v ./transformer

      - name: test-crud-mocked
        run: go test -coverprofile=coverage.out -v ./crud_handler
