name: CI Tests for database

on: [push]

jobs:

  TestForDatabase:
    name: Test and Benchmark (with db service container)
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test-database
      run: go test -coverprofile=coverage.out -v ./data-base

    - name: Benchmark
      run: go test -run=XXX -bench=. ./service

  TestAndLint:
    name: Tests and Linters
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Linters
        run: |
          curl -sSfl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

          golangci-lint run --config=golangci-lint.yml

      - name: Test-transformer
        run: go test -coverprofile=coverage.out -v ./transformer

      - name: Test-crud-mocked
        run: go test -coverprofile=coverage.out -v ./handler

      - name: Test-service
        run: go test -coverprofile=coverage.out -v ./service

      - name: Test-cache
        run: go test -coverprofile=coverage.out -v ./cache
