name: CI Tests for database

on: [push]

jobs:

  TestForDatabase:
    name: Test and Benchmark (with db service container)
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # - name: Linters
    #   run: |
    #     curl -sSfl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

    #     golangci-lint run --config=golangci-lint.yml

    - name: Tests 
      run: go test -coverprofile=coverage.out -cover -race ./... -count=1

    - name: Benchmark
      run: go test -run=XXX -bench=. ./service

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.1
