name: CI Tests

on:
  push:
    branches: [ "review_branch" ]
  pull_request:
    branches: [ "review_branch" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      links: 
        - "db:database"
      run: go test -coverprofile=coverage.out -v ./data-base
